   This Jupyter notebook gives the brief intro about how to use the Tensorflow for Deep Learning.

In [1]:
import tensorflow as tf 
import numpy as np

In [2]:
#How to create Tensors
#Constant,Variable,Placeholders(not required)

In [3]:
#Create one constant
t1=tf.constant(3)
t1

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [ ]:
#shape is 0 because only one number we have given

In [5]:
#print only number
t1.numpy()

3

In [9]:
#print rank of the given number
print('Rank of the given number is:',tf.rank(t1).numpy()) 

Rank of the given number is: 0


In [10]:
#Create a vector
t2=tf.constant([3,4,5,6,7])
t2

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([3, 4, 5, 6, 7])>

In [ ]:
#shape is 5 bcoz five numbers are given in the array

In [15]:
#access only numbers
print('Given vector is :',t2.numpy())
print('rank of the given vector is :',tf.rank(t2).numpy())  

Given vector is : [3 4 5 6 7]
rank of the given vector is : 1


In [16]:
#Create a matrix of shape 3*3
t3=tf.constant([[3,4,5],[4,1,5],[2,4,1]])
t3

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[3, 4, 5],
       [4, 1, 5],
       [2, 4, 1]])>

In [18]:
print("Given matrix is :",'\n',t3.numpy())
print('rank of the given matrix:',tf.rank(t3).numpy())

Given matrix is : 
 [[3 4 5]
 [4 1 5]
 [2 4 1]]
rank of the given matrix: 2


In [20]:
t4=tf.constant([[[3,4,5],[4,1,5],[2,4,1]],[[8,4,9],[4,1,5],[2,4,1]],[[1,4,0],[4,1,8],[2,4,1]]])
t4

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[3, 4, 5],
        [4, 1, 5],
        [2, 4, 1]],

       [[8, 4, 9],
        [4, 1, 5],
        [2, 4, 1]],

       [[1, 4, 0],
        [4, 1, 8],
        [2, 4, 1]]])>

In [21]:
#3rows ,3columns,3sets 
print("Given matrix is :",'\n',t4.numpy())
print('rank of the given matrix:',tf.rank(t4).numpy())

Given matrix is : 
 [[[3 4 5]
  [4 1 5]
  [2 4 1]]

 [[8 4 9]
  [4 1 5]
  [2 4 1]]

 [[1 4 0]
  [4 1 8]
  [2 4 1]]]
rank of the given matrix: 3


In [ ]:
#tf.constant are not editable,tf.variable can editable

In [25]:
#Create variable
tv1=tf.Variable(2,dtype=tf.float32,name='var1')
tv1

<tf.Variable 'var1:0' shape=() dtype=float32, numpy=2.0>

In [26]:
#Change the float data type to int data type
tf.cast(tv1,tf.int32)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [27]:
#Indexing
tv2=tf.Variable([2,4,6,8])

In [28]:
tv2[0]

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [29]:
tv2[3]

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [30]:
#Slicing 
tv2[:3]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 4, 6])>

In [ ]:
#tf.Tensor =it means constant, tf.Variable =it means variable

In [32]:
#Create 4*3 random numbers matrix
tv3=tf.random.normal([4,3])
tv3

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[ 0.20559284,  0.6830607 ,  1.294399  ],
       [-0.66429454,  0.45675278,  1.7638564 ],
       [-1.4845167 ,  0.52649575, -0.5825018 ],
       [-0.06285036, -1.0293989 ,  1.629944  ]], dtype=float32)>

In [33]:
tv3[0,0].assign(0)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [ ]:
#We cant assign because tv3 is constant matrix(assign function will work only for tf.variables)

In [34]:
tv4=tf.Variable(tv3)
tv4[0,0].assign(0)

<tf.Variable 'UnreadVariable' shape=(4, 3) dtype=float32, numpy=
array([[ 0.        ,  0.6830607 ,  1.294399  ],
       [-0.66429454,  0.45675278,  1.7638564 ],
       [-1.4845167 ,  0.52649575, -0.5825018 ],
       [-0.06285036, -1.0293989 ,  1.629944  ]], dtype=float32)>

In [35]:
#replace first row values with 1
tv4[0,:].assign([1,1,1])

<tf.Variable 'UnreadVariable' shape=(4, 3) dtype=float32, numpy=
array([[ 1.        ,  1.        ,  1.        ],
       [-0.66429454,  0.45675278,  1.7638564 ],
       [-1.4845167 ,  0.52649575, -0.5825018 ],
       [-0.06285036, -1.0293989 ,  1.629944  ]], dtype=float32)>

In [36]:
#Create 4*4 zero matrix
tf.zeros([4,4])

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [37]:
#reshape tv4 matrix  into 6*2
tf.reshape(tv4,[6,2])

<tf.Tensor: shape=(6, 2), dtype=float32, numpy=
array([[ 1.        ,  1.        ],
       [ 1.        , -0.66429454],
       [ 0.45675278,  1.7638564 ],
       [-1.4845167 ,  0.52649575],
       [-0.5825018 , -0.06285036],
       [-1.0293989 ,  1.629944  ]], dtype=float32)>

In [38]:
#Check values which are less than 0
tv3<0

<tf.Tensor: shape=(4, 3), dtype=bool, numpy=
array([[False, False, False],
       [ True, False, False],
       [ True, False,  True],
       [ True,  True, False]])>

In [39]:
#print values which are less than 0
tv3[tv3<0]

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([-0.66429454, -1.4845167 , -0.5825018 , -0.06285036, -1.0293989 ],
      dtype=float32)>

In [40]:
#print the position of the values which are less than 0
tf.where(tv3<0)

<tf.Tensor: shape=(5, 2), dtype=int64, numpy=
array([[1, 0],
       [2, 0],
       [2, 2],
       [3, 0],
       [3, 1]], dtype=int64)>

In [ ]:
#[1,0]   means 1st row,0th column
#[2,0]  means 2nd row ,0th column

#### Arithmetic Operations

In [42]:
a=tf.Variable([2.,3,1])
b=tf.Variable([3.,4,1])

In [43]:
#addition 
print(a+b)

tf.Tensor([5. 7. 2.], shape=(3,), dtype=float32)


In [47]:
#print only numbers
#Do all operations
print('Addition:',(a+b).numpy())
print('Multiplication:',(a*b).numpy())
print('Subtraction:',(a-b).numpy())
print('Division:',(a/b).numpy())

Addition: [5. 7. 2.]
Multiplication: [ 6. 12.  1.]
Subtraction: [-1. -1.  0.]
Division: [0.6666667 0.75      1.       ]


In [48]:
tf.tensordot(a,b,1)  #dot product:elementwise multiplication and then addition of each product

<tf.Tensor: shape=(), dtype=float32, numpy=19.0>

In [49]:
 tf.tensordot(a,b,0)   #matrix multipliction  (row*column)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 6.,  8.,  2.],
       [ 9., 12.,  3.],
       [ 3.,  4.,  1.]], dtype=float32)>

In [52]:
print(tf.pow(a,2))
print(tf.sqrt(a))
print(tf.exp(a,0.5))
print(tf.math.log(a))

tf.Tensor([4. 9. 1.], shape=(3,), dtype=float32)
tf.Tensor([1.4142135 1.7320508 1.       ], shape=(3,), dtype=float32)
tf.Tensor([ 7.389056  20.085537   2.7182817], shape=(3,), dtype=float32)
tf.Tensor([0.6931472 1.0986123 0.       ], shape=(3,), dtype=float32)


In [54]:
#print 4*4 matrix,whose values are less than 5
m1=tf.Variable(np.random.randint(1,5,[4,4]))  
m2=tf.Variable(np.random.randint(1,5,[4,4]))

In [59]:
print(m1.numpy(),'\n-----------\n',m2.numpy())

[[1 4 1 1]
 [3 4 3 3]
 [2 4 2 4]
 [4 1 2 3]] 
-----------
 [[1 2 3 4]
 [1 3 4 2]
 [2 1 1 3]
 [3 2 1 3]]


In [60]:
m1*m2  #elmentwise multiplication 

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[ 1,  8,  3,  4],
       [ 3, 12, 12,  6],
       [ 4,  4,  2, 12],
       [12,  2,  2,  9]])>

In [61]:
tf.matmul(m1,m2)    #matrix multiplication:like first row of first matrix with first column of the second matrix

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[10, 17, 21, 18],
       [22, 27, 31, 38],
       [22, 26, 28, 34],
       [18, 19, 21, 33]])>

In [62]:
#find determinant
tf.linalg.det(m1)  #here m1 is int and det is fraction value so convert m1 matrix to float

InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: half, float, double, complex64, complex128
	; NodeDef: {{node MatrixDeterminant}}; Op<name=MatrixDeterminant; signature=input:T -> output:T; attr=T:type,allowed=[DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:MatrixDeterminant]

In [63]:
m1=tf.cast(m1,tf.float32)
tf.linalg.det(m1)

<tf.Tensor: shape=(), dtype=float32, numpy=-32.0>

In [64]:
#find eigen value
tf.linalg.eigvals(m1)

<tf.Tensor: shape=(4,), dtype=complex64, numpy=
array([ 0.53225076-1.2491966e+00j,  0.53225076+1.2491968e+00j,
       -1.6409671 +0.0000000e+00j, 10.576469  -2.0463631e-11j],
      dtype=complex64)>

In [65]:
#find transpose
tf.transpose(m1)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 3., 2., 4.],
       [4., 4., 4., 1.],
       [1., 3., 2., 2.],
       [1., 3., 4., 3.]], dtype=float32)>

In [67]:
#concatenate
m2=tf.cast(m2,tf.float32)
tf.concat([m1,m2],1) 

<tf.Tensor: shape=(4, 8), dtype=float32, numpy=
array([[1., 4., 1., 1., 1., 2., 3., 4.],
       [3., 4., 3., 3., 1., 3., 4., 2.],
       [2., 4., 2., 4., 2., 1., 1., 3.],
       [4., 1., 2., 3., 3., 2., 1., 3.]], dtype=float32)>

In [ ]:
#Perform the following equation
#upd_avg=alpha*raw_data+(1-alpha)*previous_upd_avg

In [70]:
raw_data=tf.random.normal([100])
#raw_data.numpy()
alpha=tf.constant(0.05)
upd_avg=tf.Variable(0.)
res=[]



In [71]:
for i in range(raw_data.numpy().shape[0]):
    upd_avg=alpha*raw_data.numpy()[i]+(1-alpha)*upd_avg
    res.append(upd_avg.numpy())

In [72]:
import matplotlib.pyplot as plt
plt.plot(res)

In [76]:
#Single derivative
x=tf.constant(3.0)
with tf.GradientTape() as g:
    g.watch(x)
    loss=x**2
    
dloss_dx=g.gradient(loss,x) 
print(dloss_dx)

tf.Tensor(6.0, shape=(), dtype=float32)


In [77]:
#double derivative
x=tf.constant(3.0)
with tf.GradientTape() as g:
    g.watch(x)
    with tf.GradientTape() as gg:
        gg.watch(x)
        loss =x**2
    dloss_dx=gg.gradient(loss,x)
    
dloss_dx2=g.gradient(dloss_dx,x)    
    
print(dloss_dx2)    

tf.Tensor(2.0, shape=(), dtype=float32)


                                             -----Thank you-----